[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_grounds = "DuqczLjqGbTENegYpNSrT8j4PWNdqLetcQH5KGiM8wdo"  # Use your Devnet program ID

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"  # Use the Devnet cluster
wallet = "~/.config/solana/id.json"        # Ensure your devnet wallet is properly configured

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
